### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by phuwn** [phuwn/til#2]
## Find out:
- [ ] ERD
- [ ] Google OAuth 2.0
- [ ] FCM
- [ ] JWT
- [ ] The Clean code
- [ ] Go Tour
- [ ] Go By Example
- [x] validate is_approver for API request
